# Generated by Django 3.2.7 on 2023-10-13 03:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=20, verbose_name='НОМЕР ТЕЛЕФОНА')),
                ('telegram_chat_id', models.BigIntegerField(unique=True, verbose_name='ID ТЕЛЕГРАММ')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'СПЕЦИАЛИСТ',
                'verbose_name_plural': 'СПЕЦИАЛИСТЫ',
            },
        ),
        migrations.CreateModel(
            name='SpecialistCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50, verbose_name='ОТДЕЛ')),
            ],
            options={
                'verbose_name': 'КАТЕГОРИЯ СПЕЦИАЛИСТА',
                'verbose_name_plural': 'КАТЕГОРИИ СПЕЦИАЛИСТОВ',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='тест')),
            ],
            options={
                'verbose_name': ' тест',
                'verbose_name_plural': 'тесты',
            },
        ),
        migrations.CreateModel(
            name='UserTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(verbose_name='баллы')),
                ('answers', models.JSONField(default=dict, verbose_name='Ответы пользователя')),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.specialist')),
            ],
            options={
                'verbose_name': 'результат',
                'verbose_name_plural': 'результаты',
            },
        ),
        migrations.AddField(
            model_name='specialist',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.specialistcategory', verbose_name='ОТДЕЛ'),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='вопрос')),
                ('answer_choices', models.JSONField(help_text='Сохранить варианты ответов как JSON, ["Ответ 1", "Ответ 2", "Ответ 3"]', verbose_name='варианты ответов')),
                ('correct_answer', models.CharField(help_text='Текст правильного ответа', max_length=255)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.test', verbose_name='тест')),
            ],
            options={
                'verbose_name': 'вопрос',
                'verbose_name_plural': 'вопросы',
            },
        ),
    ]
